#!/usr/bin/env python3
"""Render assets/meshstar-logo.png into 1-bit bitmaps for the OLED splash
(examples/common/logo.rs): the star emblem at 40x40 and the wordmark at
128x23. Row-major, 1 bit per pixel, MSB = leftmost pixel, rows padded to
whole bytes."""
from PIL import Image, ImageFilter
import sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
im = Image.open(root / 'assets/meshstar-logo.png').convert('RGBA')

def mono(img, w, h, thr):
    sm = img.resize((w, h), Image.LANCZOS)
    rows = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b, a = sm.getpixel((x, y))
            lum = (0.3 * r + 0.59 * g + 0.11 * b) * a / 255
            row.append(lum > thr)
        rows.append(row)
    return rows

def pack(rows):
    out = []
    for row in rows:
        bits = row + [False] * ((8 - len(row) % 8) % 8)
        for i in range(0, len(bits), 8):
            v = 0
            for b in bits[i:i + 8]:
                v = (v << 1) | int(b)
            out.append(v)
    return out

# Emblem: thicken the thin arcs before downscaling.
emb = im.crop((100, 125, 570, 575))
L = Image.composite(emb.convert('L'), Image.new('L', emb.size, 0), emb.getchannel('A')).filter(ImageFilter.MaxFilter(9))
emb = Image.merge('RGBA', (L, L, L, Image.new('L', emb.size, 255)))
emblem = mono(emb, 40, 40, 100)
word = mono(im.crop((580, 200, 1975, 450)), 128, 23, 90)

def rs(name, rows, w):
    data = pack(rows)
    lines = [f"pub const {name}_W: usize = {w};", f"pub const {name}_H: usize = {len(rows)};", f"pub static {name}: [u8; {len(data)}] = ["]
    bpr = (w + 7) // 8
    for i in range(0, len(data), bpr):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + bpr]) + ",")
    lines.append("];")
    return "\n".join(lines)

out = "//! MeshStar logo bitmaps for the OLED splash. Generated by\n//! `tools/logo_to_rs.py` from `assets/meshstar-logo.png`; do not edit.\n\n" + rs("EMBLEM", emblem, 40) + "\n\n" + rs("WORDMARK", word, 128) + "\n"
(root / 'examples/common/logo.rs').write_text(out)
print("wrote examples/common/logo.rs")
